name: 湯婆婆

on:
  workflow_dispatch:
    inputs:
      name:
        description: '契約書だよ。そこに名前を書きな。'
        required: false

jobs:
  keiyaku:
    runs-on: ubuntu-latest
    steps:
      - name: フン。${{ github.event.inputs.name }}というのかい。贅沢な名だねぇ。
        id: rnd
        run: |
          set -eu
          name='${{ github.event.inputs.name }}'
          random=$[RANDOM % ${#name}]
          echo ::set-output name=new_name::${name:random:1}
      - name: 今からお前の名前は${{ steps.rnd.outputs.new_name }}だ。いいかい、${{ steps.rnd.outputs.new_name }}だよ。分かったら返事をするんだ、${{ steps.rnd.outputs.new_name }}!!
        run: echo '::debug::Convert ${{ github.event.inputs.name }} to ${{ steps.rnd.outputs.new_name }}.'
