name: 湯婆婆(マスク)

on:
  workflow_dispatch:
    inputs:
      name:
        description: '契約書だよ。そこに名前を書きな。'
        required: false

jobs:
  keiyaku:
    runs-on: ubuntu-latest
    steps:
      - name: フン。****というのかい。贅沢な名だねぇ。
        id: rnd
        run: |
          set -eu
          echo "::add-mask::$INPUT_NAME"
          random=$[RANDOM % ${#INPUT_NAME}]
          echo ::set-output name=new_name::${name:random:1}
          echo "ありがとう 千尋。僕の名前は「$INPUT_NAME」" > hidden_name.txt
      - name: 今からお前の名前は${{ steps.rnd.outputs.new_name }}だ。いいかい、${{ steps.rnd.outputs.new_name }}だよ。分かったら返事をするんだ、${{ steps.rnd.outputs.new_name }}!!
        uses: actions/upload-artifact@v2.2.0
        with:
          name: hidden_name
          path: hidden_name.txt
